In [7]:
import time

import numpy as np
import torch
import torch.nn as nn
import torch.utils.data as data

from torch import Tensor
from tqdm.notebook import tqdm  # Progress bar

In [3]:
print(torch.__version__)

1.13.0+cu117


In [10]:
torch.manual_seed(42)

In [13]:
x = Tensor([[1,2], [3,4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
x = Tensor(2,3,4)  # rank 3 tensor with dim 2,3,4
print(x)

tensor([[[ 2.0074e-35,  0.0000e+00, -6.4724e-04,  4.5902e-41],
         [ 8.9683e-44,  0.0000e+00,  1.1210e-43,  0.0000e+00],
         [ 1.9631e-35,  0.0000e+00,  7.7071e-44,  6.4460e-44]],

        [[ 6.8664e-44,  7.5670e-44,  7.5670e-44,  1.2612e-43],
         [ 1.5695e-43,  0.0000e+00,  1.5695e-43,  0.0000e+00],
         [ 1.9759e-35,  0.0000e+00,  8.9683e-44,  0.0000e+00]]])


In [19]:
print(f"{x.shape=}")

print(f"{x.size()=}")

dim1, dim2, dim3 = x.size()
print(f"{dim1=} {dim2=} {dim3=}")

x.shape=torch.Size([2, 3, 4])
x.size()=torch.Size([2, 3, 4])
dim1=2 dim2=3 dim3=4


In [21]:
x1 = torch.rand(2,3)
x2 = torch.rand(2,3)

x3 = x1 + x2  # return
x1.add_(x2)  # update x1 inplace.. in general _ suffix is inplace operations
x1, x2, x3

(tensor([[1.1360, 1.1952, 1.0107],
         [0.8708, 1.1824, 1.4056]]),
 tensor([[0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317]]),
 tensor([[1.1360, 1.1952, 1.0107],
         [0.8708, 1.1824, 1.4056]]))

In [28]:
x = torch.arange(10)
print(x)
x = x.view(2,5)  # same as reshape
print(x)
x = x.permute(1,0)  # swap dimension 0 and 1 (same as x.T in this case)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])
